# -*- coding: utf-8 -*-
"""firstlab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VASD2vUIcvDJU6vXMnpwczv20kHywYfz
"""

# slowniy kod
import string

alphabet = string.ascii_lowercase
shift = 7


def crypt(text):
    shift = 7
    rez = ""
    for c in text:
        if c != ' ':
            i = alphabet.index(c)
            i = (i + shift + len(alphabet)) % len(alphabet)
            rez = rez + alphabet[i]
            shift = ord(alphabet[i]) - ord('a')
        else:
            rez = rez + " "
    return rez


def decrypt(text):
    shift = 7
    rez = ""
    for c in text:
        if c != ' ':
            i = alphabet.index(c)
            i = (i - shift + len(alphabet)) % len(alphabet)
            rez = rez + alphabet[i]
            shift = ord(c) - ord('a')
        else:
            rez = rez + " "
    return rez;


in_str = "hello world"
out_str = crypt(in_str)
print(out_str)
print(decrypt(out_str))

# obi4niy kod
import string

alphabet = string.ascii_lowercase
shift=7

def crypt(text):
    rez=""
    for c in text:
        if c != " ":
            i=alphabet.find(c)
            i= (i+shift+len(alphabet)) % len(alphabet)
            rez=rez+alphabet[i]
        else:
             rez=rez+" "
    return rez


def decrypt(text):
    rez=""
    for c in text:
        if c != " ":
            i=alphabet.find(c)
            i= (i-shift+len(alphabet)) % len(alphabet)
            rez=rez+alphabet[i]
        else:
             rez=rez+" "
    return rez


in_str = "hello world"
out_str=crypt(in_str)
print(out_str)
print(decrypt(out_str))